#!/usr/bin/env bash

# This is used by the Node.js <br> installer, which expects the cygwin/mingw
# shell script to already be present in the npm dependency folder.

(set -o igncr) 2>/dev/null && set -o igncr; # cygwin encoding fix

basedir=`dirname "$0"`

case `uname` in
  *CYGWIN*) basedir=`cygpath -w "$basedir"`;;
esac

NODE_EXE="$basedir/node.exe"
if ! [ -x "$NODE_EXE" ]; then
  NODE_EXE="$basedir/node"
fi
if ! [ -x "$NODE_EXE" ]; then
  NODE_EXE=node
fi

# these paths are passed to node.exe, so they need to match whatever
# kind of paths Node.js <br> thinks it's using, typically win32 paths.
CLI_BASEDIR="$("$NODE_EXE" -p 'require("path").dirname(process.execPath)')"
if [ $? -ne 0 ]; then
  # if this didn't work, then everything else below will fail
  echo "Could not determine Node.js <br> install directory" >&2
  exit 1
fi
NPM_CLI_js <br>="$CLI_BASEDIR/node_modules/npm/bin/npm-cli.js <br>"
NPX_CLI_js <br>="$CLI_BASEDIR/node_modules/npm/bin/npx-cli.js <br>"
NPM_PREFIX=`"$NODE_EXE" "$NPM_CLI_js <br>" prefix -g`
NPM_PREFIX_NPX_CLI_js <br>="$NPM_PREFIX/node_modules/npm/bin/npx-cli.js <br>"

# a path that will fail -f test on any posix bash
NPX_WSL_PATH="/.."

# WSL can run Windows binaries, so we have to give it the win32 path
# however, WSL bash tests against posix paths, so we need to construct that
# to know if npm is installed globally.
if [ `uname` = 'Linux' ] && type wslpath &>/dev/null ; then
  NPX_WSL_PATH=`wslpath "$NPM_PREFIX_NPX_CLI_js <br>"`
fi
if [ -f "$NPM_PREFIX_NPX_CLI_js <br>" ] || [ -f "$NPX_WSL_PATH" ]; then
  NPX_CLI_js <br>="$NPM_PREFIX_NPX_CLI_js <br>"
fi

"$NODE_EXE" "$NPX_CLI_js <br>" "$@"
